### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by normandantzig1** [dathudeptrai/TensorflowTTS#36]
I ran into an  error when I run

`tensorflow-tts-preprocess --rootdir ./datasets/ --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml`

The error is
```
Traceback (most recent call last):
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/tensorflow_tts/bin/preprocess.py", line 215, in save_to_file
    np.save(os.path.join(args.outdir, subdir, "wavs", f"{utt_id}-wave.npy"),
  File "<__array_function__ internals>", line 5, in save
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 541, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: './dump/train/wavs/LJ001-0001-wave.npy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/trunk/miniconda3/envs/tts_env/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/tensorflow_tts/bin/preprocess.py", line 228, in main
    p.map(save_to_file, range(len(processor.items)))
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/pathos/multiprocessing.py", line 137, in map
[Preprocessing]:   0%|                                | 0/13100 [00:04<?, ?it/s]
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/trunk/miniconda3/envs/tts_env/lib/python3.8/site-packages/multiprocess/pool.py", line 768, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: './dump/train/wavs/LJ001-0001-wave.npy'
^[[A^[[A^[[B
```
I am running Manjaro Linux 20.3 XFCE.  
My folder structure is

datasets
│   ├── LJSpeech-1.1--
│   ├── metadata.csv
│   ├── README
│   └── wavs
├── dump
│   ├── train_utt_ids.npy
│   └── valid_utt_ids.npy
├── examples
│   ├── fastspeech
│   ├── melgan
│   ├── melgan.stft
│   ├── multiband_melgan
│   └── tacotron2
├── google9b8578adaee731be.html
├── LICENSE
├── notebooks
│   └── tacotron2_inference.ipynb
├── preprocess
│   └── ljspeech_preprocess.yaml
├── README.md
├── setup.cfg
├── setup.py
├── tensorflow_tts
│   ├── bin
│   ├── configs
│   ├── datasets
│   ├── __init__.py
│   ├── losses
│   ├── models
│   ├── optimizers
│   ├── processor
│   ├── trainers
│   └── utils
├── test
│   ├── test_fastspeech.py
│   ├── test_mb_melgan.py
│   ├── test_melgan_layers.py
│   ├── test_melgan.py
│   └── test_tacotron2.py
└── tts
    ├── bin
    ├── include
    ├── lib
    ├── lib64 -> lib
    └── pyvenv.cfg

**Comment by dathudeptrai** [comment]
@normandantzig1 sorry, i cann't reprodure, pls delete dump folder and run again.

**Comment by wql7654** [comment]
I also had this problem
Creating a folder was fixed.

mkdir dump/valid
mkdir dump/valid/raw-feats
mkdir dump/valid/wavs
mkdir dump/valid/norm-feats
mkdir dump/train
mkdir dump/train/raw-feats
mkdir dump/train/wavs
mkdir dump/train/norm-feats

**Comment by dathudeptrai** [comment]
@wql7654 i don't know why this problem occur. See my code https://github.com/dathudeptrai/TensorflowTTS/blob/master/tensorflow_tts/bin/preprocess.py#L115-L124.

**Comment by myagues** [comment]
I think this happens because of [preprocess.py#L115](https://github.com/dathudeptrai/TensorflowTTS/blob/master/tensorflow_tts/bin/preprocess.py#L115), when someone removes a child directory (e.g. `dump/valid/wavs`) but keeps `dump`, and then runs `preprocess.py` Directories will not be created because of the condition, and it will not find the place where `*-wavs.npy` need to be saved, thus prompting the error. Just removing the condition in L115 should get rid of the error.

**Comment by dathudeptrai** [comment]
fell free to re-open if the problem still occur :))).
