### ISSUE TITLE
Help me learn Melgan.

### ISSUE THREAD

**Issue by junryge** [dathudeptrai/TensorflowTTS#48]
Melgan learning is not possible.
It says there is no voice file.
Help me.

![111](https://user-images.githubusercontent.com/66813375/85018801-ba832380-b1a8-11ea-9f4f-e39051d62019.JPG)

**Comment by dathudeptrai** [comment]
did you follow with my preprocessin steps ?. here, https://github.com/dathudeptrai/TensorflowTTS#preprocessing. Pls check if there is a folder named ./dump/train/wavs/

**Comment by junryge** [comment]
Yes, I did.
It's the same.
I don't know why.

![image](https://user-images.githubusercontent.com/66813375/85030188-1dc88200-b1b8-11ea-866e-b9d22301dd64.png)

**Comment by dathudeptrai** [comment]
wavs file should be LJ001-0001-wave.npy. You can see in my code here https://github.com/dathudeptrai/TensorflowTTS/blob/master/tensorflow_tts/bin/preprocess.py#L215-L216. The suffix of wave file is -wave.npy. I don't know why ur file don't have suffix :3

**Comment by junryge** [comment]
I'm trying to change the file name to what you're talking about.
There was an error.
*.npy

error code
(ff) D:\tensorflow_code\TensorflowTTS>tensorflow-tts-preprocess --rootdir /datasets/ --outdir /dump/ --conf preprocess/ljspeech_preprocess.yaml
2020-06-19 10:21:03.647199: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\tensorflow-tts-preprocess-script.py", line 11, in <module>
    load_entry_point('TensorflowTTS==0.0', 'console_scripts', 'tensorflow-tts-preprocess')()
  File "c:\anaconda3\lib\site-packages\tensorflowtts-0.0-py3.7.egg\tensorflow_tts\bin\preprocess.py", line 111, in main
  File "c:\anaconda3\lib\site-packages\tensorflowtts-0.0-py3.7.egg\tensorflow_tts\processor\ljspeech.py", line 54, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/metadata.csv'

(ff) D:\tensorflow_code\TensorflowTTS>tensorflow-tts-preprocess --rootdir /datasets/ --outdir /dump/ --conf preprocess/ljspeech_preprocess.yaml
2020-06-19 10:21:26.286837: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\tensorflow-tts-preprocess-script.py", line 11, in <module>
    load_entry_point('TensorflowTTS==0.0', 'console_scripts', 'tensorflow-tts-preprocess')()
  File "c:\anaconda3\lib\site-packages\tensorflowtts-0.0-py3.7.egg\tensorflow_tts\bin\preprocess.py", line 111, in main
  File "c:\anaconda3\lib\site-packages\tensorflowtts-0.0-py3.7.egg\tensorflow_tts\processor\ljspeech.py", line 54, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/metadata.csv'

(ff) D:\tensorflow_code\TensorflowTTS>tensorflow-tts-preprocess --rootdir ./datasets/ --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml
2020-06-19 10:22:13.787136: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
[Preprocessing]:   0%|                                                                                                     | 0/13100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\tensorflow-tts-preprocess-script.py", line 11, in <module>
    load_entry_point('TensorflowTTS==0.0', 'console_scripts', 'tensorflow-tts-preprocess')()
  File "c:\anaconda3\lib\site-packages\tensorflowtts-0.0-py3.7.egg\tensorflow_tts\bin\preprocess.py", line 228, in main
  File "c:\anaconda3\lib\site-packages\pathos-0.2.6-py3.7.egg\pathos\multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "c:\anaconda3\lib\site-packages\multiprocess-0.70.10-py3.7.egg\multiprocess\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\anaconda3\lib\site-packages\multiprocess-0.70.10-py3.7.egg\multiprocess\pool.py", line 657, in get
    raise self._value
  File "c:\anaconda3\lib\site-packages\multiprocess-0.70.10-py3.7.egg\multiprocess\pool.py", line 431, in _handle_tasks
    put(task)
  File "c:\anaconda3\lib\site-packages\multiprocess-0.70.10-py3.7.egg\multiprocess\connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "c:\anaconda3\lib\site-packages\multiprocess-0.70.10-py3.7.egg\multiprocess\reduction.py", line 54, in dumps
    cls(buf, protocol, *args, **kwds).dump(obj)
  File "c:\anaconda3\lib\site-packages\dill-0.3.2-py3.7.egg\dill\_dill.py", line 446, in dump
    StockPickler.dump(self, obj)
  File "C:\Anaconda3\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 789, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\anaconda3\lib\site-packages\dill-0.3.2-py3.7.egg\dill\_dill.py", line 1438, in save_function
    obj.__dict__, fkwdefaults), obj=obj)
  File "C:\Anaconda3\lib\pickle.py", line 638, in save_reduce
    save(args)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 789, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\anaconda3\lib\site-packages\dill-0.3.2-py3.7.egg\dill\_dill.py", line 1170, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)
  File "C:\Anaconda3\lib\pickle.py", line 638, in save_reduce
    save(args)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\anaconda3\lib\site-packages\dill-0.3.2-py3.7.egg\dill\_dill.py", line 1438, in save_function
    obj.__dict__, fkwdefaults), obj=obj)
  File "C:\Anaconda3\lib\pickle.py", line 638, in save_reduce
    save(args)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 789, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 789, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\anaconda3\lib\site-packages\dill-0.3.2-py3.7.egg\dill\_dill.py", line 1170, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)
  File "C:\Anaconda3\lib\pickle.py", line 638, in save_reduce
    save(args)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Anaconda3\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Anaconda3\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Anaconda3\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\anaconda3\lib\site-packages\dill-0.3.2-py3.7.egg\dill\_dill.py", line 933, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Anaconda3\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Anaconda3\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Anaconda3\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: cannot serialize '_io.TextIOWrapper' object
[Preprocessing]:   0%|                                                                                                     | 0/13100 [00:00<?, ?it/s]
--------------------------------------------------------------------------------------------
I don't understand.
Please. Can you help me?

**Comment by dathudeptrai** [comment]
can you change dill to 0.3.1.1 and pathos to 0.2.5 version ?

**Comment by junryge** [comment]
Now you are changing the version to what you are talking about..

The symptoms are the same.

Should I use Ubuntu program?



![image](https://user-images.githubusercontent.com/66813375/85089635-189e1e00-b21e-11ea-9511-a1848ae21fe0.png)
![image](https://user-images.githubusercontent.com/66813375/85089651-2653a380-b21e-11ea-949b-a6a21c6c5ac9.png)

**Comment by dathudeptrai** [comment]
i never test it in window @@.

**Comment by junryge** [comment]
I'll try Ubuntu.

Challenge

**Comment by junryge** [comment]
I'll try Ubuntu.

**Comment by junryge** [comment]
I'll try to make a window.
